### ISSUE TITLE
inconsistent bold letters 粗体字不一致

### ISSUE THREAD

**Issue by Ludo55** [wy-luke/Unity-TextMeshPro-Chinese-Characters-Set#3]
I'm getting inconsistencies where bold text is not matching on the letters that have diacritics.
我遇到了不一致的情况，即粗体文本与带有变音符号的字母不匹配

![need to fix 1](https://github.com/wy-luke/Unity-TextMeshPro-Chinese-Characters-Set/assets/103251960/131caa3a-7f04-4e2b-8145-095080897a6c)

**Comment by wy-luke** [comment]
不太理解你要表达的意思，期望的样式是什么样子的？全部是粗体？

**Comment by Ludo55** [comment]
yes, all in bold. but the pinyin letters are inconsistent. some letters are more bold than others. 
是的，全部用粗体显示。 但拼音字母不一致。 有些字母比其他字母更粗体。

**Comment by wy-luke** [comment]
你把字体发我看看呢 @Ludo55 
Send me the font you used, plz. Let me look look what happened.

**Comment by Ludo55** [comment]
Thanks for your help.  I don't know what caused it, but It seems to have solved itself. 
it was probably an error due to my own mistake. 
![image](https://github.com/wy-luke/Unity-TextMeshPro-Chinese-Characters-Set/assets/103251960/7c4645e2-3d81-459a-a772-fd09c57b964a)
