### ISSUE TITLE
英文单词如果有空格，空格后的单词不会显示

### ISSUE THREAD

**Issue by zhuangjia777** [wy-luke/Unity-TextMeshPro-Chinese-Characters-Set#7]
比如 ”START MENU“只显示”START“

**Comment by wy-luke** [comment]
很抱歉我已经有段时间不使用Unity了，不能给你提供其他帮助了，我简单查了一下，没有查到相关问题

我又验证了一下，字符集里面是包含两种空格的，这个应该是Unity的问题，可以去他们那边问一下

https://forum.unity.com/forums/ugui-textmesh-pro.60/

**Comment by lsx1994** [comment]
做好的字库里没空格吧， 自己生成一下。
